#!/bin/sh

alias ls='ls --color=auto'
alias grep='grep --color=auto'

# easily edit and compile dwm
alias cdwm='nvim ~/.local/src/dwm/config.h'
alias mdwm='cd ~/.local/src/dwm/ && sudo make clean install && cd -'

# dotfiles mangement
alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias cfg='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

alias v='nvim'
alias vi='nvim'
alias vim='nvim'

# music sl
alias mdl='yt-dlp -t mp3 --embed-thumbnail --add-metadata --metadata-from-title "%(title)s" --parse-metadata "title:%(title)s" --parse-metadata "uploader:%(artist)s" --output "~/input/%(artist)s/%(album)s/%(artist)s - %(title)s.%(ext)s" '
