#!/bin/sh

alias ls='ls --color=auto'
alias grep='grep --color=auto'

alias otp='pass otp'

# easily edit and compile dwm
alias cdwm='nvim ~/.local/src/dwm/config.h'
alias mdwm='cd ~/.local/src/dwm/ && sudo make clean install && cd -'

# dotfiles mangement
alias config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'
alias c='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'

alias v='nvim'
alias vi='nvim'
alias vim='nvim'
